### ISSUE TITLE
Obsolete rule causes typescript eslint to fail

### ISSUE THREAD

**Issue by bogmir** [devonfw/devon4node#348] opened 2020-10-21 21:41 UTC
### Expected behavior

The rule '@typescript-eslint/interface-name-prefix': 'off', defined in .eslintrc.js should enforce an interface naming rule. 

### Actual behavior

This rule has been removed in @typescript-eslint latest versions, causing the linter to not work as expected. It invalidates all JS files instead.

### Comments/Hints:
Use latest recommended rule definition:

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-interface-names-do-not-begin-with-an-i

**Comment by NilsLeger** [comment] 2021-01-30 07:26
Is this issue _recognized and accepted by somebody from the community_? If so, this is a great starting point for me to contribute to devon4node. So if it is accepted, please assign it to me.

**Comment by sjimenez77** [comment] 2021-04-27 14:20
Hi @NilsLeger, sorry for the very late reply. Unfortunately we have been focused more on other urgent issues during the last months, but we are working to recover some of the activities and devon4node maintenance and development is indeed an important part of our devonfw assets. It would be great if you are still interested on contributing via PRs. 

Please, let us know and I will assign this issue to you then.

**Comment by NilsLeger** [comment] 2021-04-27 15:29
Hi @sjimenez77, I'm still interested in contributing. Don't hesitate to assign this issue to me.

**Comment by NilsLeger** [comment] 2021-05-01 07:31
Hi @sjimenez77,

### Reproduction
I could reproduce the problem. If `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` versions are increased from `2.22.0` to `4.22.0`, an error occurs telling that `@typescript-eslint/interface-name-prefix` is an unknown rule, and invalidating all `.js` files at the same time.

Now, replacing `@typescript-eslint/interface-name-prefix` with what is recommended [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-interface-names-do-not-begin-with-an-i), fixes the problem if version `4.22.0` for `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` is used.

But switching back to version `2.22.0` showed that now, with the updated `.eslintrc.js`, the rule `@typescript-eslint/eslint-plugin` will invalidate all interfaces with the prefix "I" again, because this rule is enabled by default.

### Conclusion
Replacing `@typescript-eslint/interface-name-prefix` would fix the problem for users that use the latest `@typescript-eslint` versions but at the same time, introduce problems to users who use the version `2.22.0`.
So, 
* either we increase the version for `@typescript-eslint` **and** replace `@typescript-eslint/interface-name-prefix`
* or we leave it as it is and users, who decide to increase their `@typescript-eslint` version, have to fix the problems themselves

**Comment by sjimenez77** [comment] 2021-05-05 13:28
Ok, thanks @NilsLeger for the analysis. Let's then wait, since there is a planned big upgrade in the incoming weeks and we can leave this issue opened for the moment just to inform users that may face the same issue with current version. After upgrade we can close this.

**Closed** 2021-06-07 18:03 UTC
Labels: bug
